# Generated by Django 6.0.5 on 2026-05-27 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="nickname",
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
